"""category added

Revision ID: 214ffd8e7725
Revises: 31b9ccc193e2
Create Date: 2023-05-14 02:02:08.281078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '214ffd8e7725'
down_revision = '31b9ccc193e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('post_no', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categorise')
    # ### end Alembic commands ###
