"""email  table

Revision ID: 34f9b645bb2d
Revises: a0c87ca66c63
Create Date: 2023-05-20 23:03:37.995738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34f9b645bb2d'
down_revision = 'a0c87ca66c63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=250), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('email', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['categorise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emails')
    # ### end Alembic commands ###
